H0_6(1,1) = - sin(th(6))*(cos(th(4))*sin(th(1)) - sin(th(4))*(cos(th(1))*cos(th(2))*sin(th(3)) - cos(th(1))*cos(th(3))*sin(th(2)))) - cos(th(6))*(sin(th(5))*(sin(th(1))*sin(th(4)) + cos(th(4))*(cos(th(1))*cos(th(2))*sin(th(3)) - cos(th(1))*cos(th(3))*sin(th(2)))) + cos(th(5))*(cos(th(1))*sin(th(2))*sin(th(3)) + cos(th(1))*cos(th(2))*cos(th(3))));
H0_6(1,2) =sin(th(6))*(sin(th(5))*(sin(th(1))*sin(th(4)) + cos(th(4))*(cos(th(1))*cos(th(2))*sin(th(3)) - cos(th(1))*cos(th(3))*sin(th(2)))) + cos(th(5))*(cos(th(1))*sin(th(2))*sin(th(3)) + cos(th(1))*cos(th(2))*cos(th(3)))) - cos(th(6))*(cos(th(4))*sin(th(1)) - sin(th(4))*(cos(th(1))*cos(th(2))*sin(th(3)) - cos(th(1))*cos(th(3))*sin(th(2))));
H0_6(1,3) =cos(th(5))*(sin(th(1))*sin(th(4)) + cos(th(4))*(cos(th(1))*cos(th(2))*sin(th(3)) - cos(th(1))*cos(th(3))*sin(th(2)))) - sin(th(5))*(cos(th(1))*sin(th(2))*sin(th(3)) + cos(th(1))*cos(th(2))*cos(th(3)));
H0_6(1,4) =l2*cos(th(1)) + (l7 + l8)*(cos(th(5))*(sin(th(1))*sin(th(4)) + cos(th(4))*(cos(th(1))*cos(th(2))*sin(th(3)) - cos(th(1))*cos(th(3))*sin(th(2)))) - sin(th(5))*(cos(th(1))*sin(th(2))*sin(th(3)) + cos(th(1))*cos(th(2))*cos(th(3)))) + (l5 + l6)*(cos(th(1))*sin(th(2))*sin(th(3)) + cos(th(1))*cos(th(2))*cos(th(3))) + l4*cos(th(1))*sin(th(2));
H0_6(2,1) =sin(th(6))*(cos(th(1))*cos(th(4)) + sin(th(4))*(cos(th(2))*sin(th(1))*sin(th(3)) - cos(th(3))*sin(th(1))*sin(th(2)))) + cos(th(6))*(sin(th(5))*(cos(th(1))*sin(th(4)) - cos(th(4))*(cos(th(2))*sin(th(1))*sin(th(3)) - cos(th(3))*sin(th(1))*sin(th(2)))) - cos(th(5))*(sin(th(1))*sin(th(2))*sin(th(3)) + cos(th(2))*cos(th(3))*sin(th(1))));
H0_6(2,2) =cos(th(6))*(cos(th(1))*cos(th(4)) + sin(th(4))*(cos(th(2))*sin(th(1))*sin(th(3)) - cos(th(3))*sin(th(1))*sin(th(2)))) - sin(th(6))*(sin(th(5))*(cos(th(1))*sin(th(4)) - cos(th(4))*(cos(th(2))*sin(th(1))*sin(th(3)) - cos(th(3))*sin(th(1))*sin(th(2)))) - cos(th(5))*(sin(th(1))*sin(th(2))*sin(th(3)) + cos(th(2))*cos(th(3))*sin(th(1))));
H0_6(2,3) =- cos(th(5))*(cos(th(1))*sin(th(4)) - cos(th(4))*(cos(th(2))*sin(th(1))*sin(th(3)) - cos(th(3))*sin(th(1))*sin(th(2)))) - sin(th(5))*(sin(th(1))*sin(th(2))*sin(th(3)) + cos(th(2))*cos(th(3))*sin(th(1)));
H0_6(2,4) =(l5 + l6)*(sin(th(1))*sin(th(2))*sin(th(3)) + cos(th(2))*cos(th(3))*sin(th(1))) - (l7 + l8)*(cos(th(5))*(cos(th(1))*sin(th(4)) - cos(th(4))*(cos(th(2))*sin(th(1))*sin(th(3)) - cos(th(3))*sin(th(1))*sin(th(2)))) + sin(th(5))*(sin(th(1))*sin(th(2))*sin(th(3)) + cos(th(2))*cos(th(3))*sin(th(1)))) + l2*sin(th(1)) + l4*sin(th(1))*sin(th(2));
H0_6(3,1) =- cos(th(6))*(cos(th(5))*(cos(th(2))*sin(th(3)) - cos(th(3))*sin(th(2))) - cos(th(4))*sin(th(5))*(cos(th(2))*cos(th(3)) + sin(th(2))*sin(th(3)))) - sin(th(4))*sin(th(6))*(cos(th(2))*cos(th(3)) + sin(th(2))*sin(th(3)));
H0_6(3,2) =sin(th(6))*(cos(th(5))*(cos(th(2))*sin(th(3)) - cos(th(3))*sin(th(2))) - cos(th(4))*sin(th(5))*(cos(th(2))*cos(th(3)) + sin(th(2))*sin(th(3)))) - cos(th(6))*sin(th(4))*(cos(th(2))*cos(th(3)) + sin(th(2))*sin(th(3)));
H0_6(3,3) =- sin(th(5))*(cos(th(2))*sin(th(3)) - cos(th(3))*sin(th(2))) - cos(th(4))*cos(th(5))*(cos(th(2))*cos(th(3)) + sin(th(2))*sin(th(3)));
H0_6(3,4) =l1 + l3 + (l5 + l6)*(cos(th(2))*sin(th(3)) - cos(th(3))*sin(th(2))) - (l7 + l8)*(sin(th(5))*(cos(th(2))*sin(th(3)) - cos(th(3))*sin(th(2))) + cos(th(4))*cos(th(5))*(cos(th(2))*cos(th(3)) + sin(th(2))*sin(th(3)))) + l4*cos(th(2));
 